query accountAdminsInfo {
  accounts {
    id
    type
    host {
      id
      nameID
      profile {
        displayName
      }
      ... on Organization {
        roleSet {
          admins: usersInRole(role: ADMIN) {
            id
            nameID
            profile {
              displayName
            }
          }
          owners: usersInRole(role: OWNER) {
            id
            nameID
            profile {
              displayName
            }
          }
        }
      }
    }
    spaces {
      id
      about {
        profile {
          displayName
        }
      }
      visibility
      community {
        id
        roleSet {
          usersInRole(role: ADMIN) {
            id
            nameID
            profile {
              displayName
            }
          }
        }
      }
    }
  }
}
