query spacesLicenseUsageExcel {
  spaces(filter: { visibilities: [DEMO, ARCHIVED, ACTIVE] }) {
    id
    nameID
    about {
      profile {
        displayName
      }
    }
    visibility
    account {
      id
      type
      agent {
        credentials {
          id
          type
        }
      }
      host {
        id
        profile {
          displayName
        }
      }
    }
    community {
      id
      roleSet {
        usersInRole(role: MEMBER) {
          profile {
            displayName
          }
        }
      }
    }
    templatesManager {
      id
      templateDefaults {
        id
        template {
          id
          collaboration {
            innovationFlow {
              id
              states {
                displayName
              }
            }
          }
        }
      }
    }
    collaboration {
      id
    }
    subspaces {
      id
    }
  }
}
